'use strict';
const assert = require('node:assert/strict');
const E = require('../docs/assets/event-recovery-core');
const SP = require('../docs/assets/starpower-core');
assert.deepEqual(E.eventWindow('2020-02'), {monthStart:'20200201',monthEnd:'20200229',preCutoff:'20200131',returnStart:'20210228',alternativeStart:'20210131'});
assert.throws(()=>E.eventWindow('2020-13'));
const film=(id,date,actors,audi=100)=>({movieCd:id,movieNm:id,openDt:date,nation:'한국',audiAcc:audi,actors:actors.map(id=>({id,name:id}))});
const movies=[film('p','20180101',['a','b']),film('q','20190101',['b']),film('r','20190601',['a','c']),film('below','20210227',['a']),film('on','20210228',['a','b']),film('tie','20210228',['a','c']),film('after','20210301',['a'])];
const m=SP.buildModel(movies);
const found=E.firstReturns(m,'a','20210228');
assert.deepEqual(found.map(x=>x.movieCd),['on','tie']);
const high=E.highSynergy([{key:'x',value:9},{key:'y',value:9},{key:'z',value:-1},{key:'w',value:0}],25);
assert.deepEqual(high.keys.sort(),['x','y']);
assert.equal(E.highSynergy([{key:'a',value:-1}],25).keys.length,0);
assert.equal(E.ratio(4,0),null);
assert.equal(E.ratio(4,2),2);
const c={name:'a',id:'a',eventMonth:'2020-02',priority:1};
const before=E.analyze(movies,[c]);
const future=E.analyze([...movies,film('future','20240101',['a','b'],999999)],[c]);
assert.deepEqual(before.cases[0].preEvent, future.cases[0].preEvent,'Future releases must not change pre-event eligibility');
assert.deepEqual(before.cases[0].synergyPool, future.cases[0].synergyPool,'Future releases must not enter pre-event synergy');
assert.equal(before.cases[0].returnFilms[0].baselineCount,3,'Earlier eligible films only; same-day films excluded');
assert.equal(E.sequenceEvidence([{year:2019,state:'Hawk'},{year:2020,state:'Unknown'},{year:2021,state:'Dove'},{year:2022,state:'Hawk'}]).contiguousHDH,false);
assert.equal(E.sequenceEvidence([{year:2019,state:'Hawk'},{year:2020,state:'Dove'},{year:2021,state:'Hawk'}]).contiguousHDH,true);
// A single target/partner pair is computable only with a nonjoint partner film.
const pa=before.cases[0].synergyPool.find(x=>x.id==='b');
assert.equal(pa.withCount,1);assert.equal(pa.withoutCount,1);
assert.equal(before.cases[0].synergyPool.find(x=>x.id==='c').value,null);
assert.ok(before.cases[0].returnFilms[0].sensitivity.every(x=>x.matched.every(p=>p.value>0)));
const noReturn=E.analyze(movies.filter(m=>m.openDt<'20210101'),[c]);
assert.equal(noReturn.cases[0].returnFilms.length,0);
assert.equal(noReturn.cases[0].selected,false);
assert.ok(noReturn.cases[0].eligibilityReasons.includes('365일 이후 적격 개봉작 없음'));
assert.equal(before.cases[0].annualStates.find(x=>x.year===2020).state,'Mixed');
console.log('Event recovery tests passed');
