name: Build Movie Details & Indexes

on:
  workflow_dispatch:
    inputs:
      year_start:
        description: '시작 연도 (YYYY)'
        required: true
        type: string
      year_end:
        description: '끝 연도 (YYYY, 포함)'
        required: true
        type: string
      max_count:
        description: '최대 작업 개수 (비우면 전체)'
        required: false
        default: "999999"
        type: string
      skip_details:
        description: '상세 수집 건너뛰고 인덱스만 빌드'
        required: false
        type: boolean
        default: false
      precompute_audiacc:
        description: '인덱스/인물에 audiAcc 선계산 포함'
        required: false
        type: boolean
        default: false
      recent_days:
        description: 'recent 모드 기준 일수 (예: 120)'
        required: false
        default: "0"   # 0 이면 recent 모드 끔
        type: string

permissions:
  contents: write

concurrency:
  group: build-caches-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 상세 수집 단계 (옵션으로 건너뛰기)
      - name: Build movie details
        if: ${{ inputs.skip_details != 'true' }}
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: |
          python scripts/build_movie_details.py \
            --year-start "${{ inputs.year_start }}" \
            --year-end   "${{ inputs.year_end }}" \
            --max        "${{ inputs.max_count }}"

      # 인덱스 생성 (recent/audiAcc 옵션 전달)
      - name: Build search & people indexes
        run: |
          python scripts/build_indices.py \
            ${{ inputs.precompute_audiacc == 'true' && '--precompute-audiacc' || '' }} \
            ${{ inputs.recent_days != '0' && format('--recent-days {0}', inputs.recent_days) || '' }}

      - name: Commit caches
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -eux
          git config user.name  "actions-user"
          git config user.email "actions@github.com"
          git add docs/data
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Build caches: $GITHUB_RUN_ID"
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH" || git push --force-with-lease origin "HEAD:$BRANCH"
