name: Build Search Indexes (only)

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-indexes-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build indexes
        run: |
          python scripts/build_indices.py

      - name: Commit indexes
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name  "actions-user"
          git config user.email "actions@github.com"
          git add docs/data/search docs/data/people/unknown.json || true
          if git diff --staged --quiet; then
            echo "No index changes."
            exit 0
          fi
          git commit -m "Rebuild search & people indexes"
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH" || git push --force-with-lease origin "HEAD:$BRANCH"
