name: KOFIC Daily Fetch

on:
  schedule:
    - cron: "10 15 * * *"   # 한국시간 00:10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: python scripts/update_data.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Daily KOFIC update" || echo "No changes"
          git push
