name: KOFIC Daily Fetch

on:
  schedule:
    # 한국 시간 기준 매일 오전 9시 10분에 실행 (UTC 00:10)
    - cron: "10 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: kofic-daily
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch KOFIC Daily Box Office
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: |
          TARGET_DT=$(TZ=Asia/Seoul date -d "yesterday" +%Y%m%d)
          TARGET_DT_FMT=$(TZ=Asia/Seoul date -d "yesterday" +%Y-%m-%d)
          echo "Fetching data for $TARGET_DT"
          
          curl -s "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=${KOFIC_API_KEY}&targetDt=${TARGET_DT}" > docs/data/${TARGET_DT}.json
          
          # [수정] 잘못된 cp 명령어 대신, 올바른 JSON 형식으로 latest.json 파일을 생성
          echo "{\"url\": \"data/${TARGET_DT}.json\", \"date\": \"${TARGET_DT_FMT}\"}" > docs/data/latest.json
          
          echo "Daily box office data for $TARGET_DT and latest.json saved."

      - name: Update movie details from new daily file
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: |
          python scripts/update_data.py

      - name: Light refresh current-year details
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: |
          YEAR=$(TZ=Asia/Seoul date +%Y)
          python scripts/build_movie_details.py \
            --year-start "$YEAR" \
            --year-end   "$YEAR" \
            --max        "300"

      - name: Rebuild search indexes
        run: |
          python scripts/build_indices.py

      - name: Commit updated data
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -eux
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/
          if git diff --staged --quiet; then
            echo "No new data to commit."
            exit 0
          fi
          git commit -m "KOFIC: Daily data update"
          git push origin "HEAD:$BRANCH"
