name: KOFIC Daily Fetch

on:
  schedule:
    - cron: "10 15 * * *"   # 매일 KST 00:10 (UTC 15:10)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: kofic-daily
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and save KOFIC daily data
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
          # TARGET_DT: "20250826"  # 필요시 강제 날짜
        run: |
          python scripts/update_data.py

      # 가볍게: 현재 연도만 일부 보강 (신규 영화 상세 캐시 확보)
      - name: Light refresh current-year details
        env:
          KOFIC_API_KEY: ${{ secrets.KOFIC_API_KEY }}
        run: |
          # KST 기준 연도
          YEAR=$(TZ=Asia/Seoul date +%Y)
          python scripts/build_movie_details.py \
            --year-start "$YEAR" \
            --year-end   "$YEAR" \
            --max        "300"

      # 검색 인덱스 재생성 (movies.json / people.json)
      - name: Rebuild search indexes
        run: |
          python scripts/build_indices.py

      - name: Commit updated data
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -eux
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add docs/data/
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "Daily KOFIC update (and reindex)"
          git fetch origin "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH" || git push --force-with-lease origin "HEAD:$BRANCH"
